### ISSUE TITLE
Missing parameters in cleanLogs

### ISSUE THREAD

**Issue by Oggerschummer** [yourtion/SuperLogger#4]
When cleaning the logs from code (e.g. on App start) a parameter like "sinceDate:(NSDate*)" would be helpful as one does not always want top clean all logs but needs to keep e.g. the last week.

Same problem if you want to keep the last x logs, not possible.

In additional another parameter like "deleteCrashs" would be helpful.

Summary: How about something like "cleanLogsSince:(NSDate*) since keeping:(int)keepMaxLogs deletingCrashes:(BOOL) deleteCrashes" would make sense.

**Comment by yourtion** [comment]
It's a good idea, but I don't know how to show view better.

**Comment by Oggerschummer** [comment]
Hi,

the view itself is fine, it´s simple the API behind that is lacking the functionality.
I will look into this and may provide a solution.
Cheers,
Thomas

**Comment by yourtion** [comment]
I already working on it. I think I can finish few today.
Thank's a lot
