### ISSUE TITLE
Localization for button titles missing

### ISSUE THREAD

**Issue by Oggerschummer** [yourtion/SuperLogger#7]
Titles for buttons are not localized but carry hardcoded text

**Comment by yourtion** [comment]
Add Chinese

**Comment by Oggerschummer** [comment]
Facing issues with the IPA generated. 
Texts are not showing up as "copy resources" for cocoa pod in build somehow does not pick the files properly.
Switched to using a bundle, but currently bundle content is not copied (bundle itself is). Would keep this open for now. Hope to fix it today.
